sec-deadlines/sec-deadlines.github.io

_data/conferences.yml
This deadline is taken from the submission server (https://secure.iacr.org/websubrev/ec2018/submit/).
=> fix EUROCRYPT 18 deadline

_data/conferences.yml
As I understand the [website](https://www.ieee-security.org/TC/SP2018/), the next S&P is in 2018, and if you submit until the 1st of december, you can still be part of that conference. This PR thus dates S&P for 2018 - feel free to correct me and close this issue if I misunderstood.
=> Update IEEE S&P year to 2018

_data/conferences.yml
See CFP here: https://www.sigsac.org/ccs/CCS2018/papers.html.
As far as I know, the PDT / UTC-7 stated in the CFP should be equivalent to GMT-7, which (according to the readme) should be inverted to GMT+7. Timezones are weird, so please double-check this.
=> Add CCS deadline

_data/conferences.yml
See [CFP](https://www.ieee-security.org/TC/EuroSP2019/cfp.php).
Standard caveats apply: I have no idea if I got the timezone right. Plus, there is an abstract registration deadline on October 15th, with the final deadline almost a month later (November 13th). Not sure how to model this here, so I added the final deadline, with the abstract registration deadline as a comment (one could also consider a double-deadline similar to the quarterly PETS deadline syntax) - feel free to modify, as always.
=> Add EuroS&P

_data/conferences.yml
Updating old links and locations for Usenix/CCS to 2020.
Also adding SOUPS, the Symposium on Usable Security and Privacy.
=> Update to 2020 Usenix and CCS, add SOUPS

_data/conferences.yml
Updated the submission deadline for ACM WiSec 2020 which has been extended to 2020-03-13 23:59 (AoE)
=> WiSec 2020 extended paper submission deadline

_data/conferences.yml
These two conferences are missing the comments to flag the multiple deadlines.
=> Add missing comments for rolling deadlines (S&P, NDSS)

_data/conferences.yml
New dates for USENIX 2022 as per CFP here: [https://www.usenix.org/conference/usenixsecurity22/call-for-papers](https://www.usenix.org/conference/usenixsecurity22/call-for-papers)
=> Update USENIX 2022

_data/conferences.yml
Noticed that the deadline for PETS 2021 was after the conference. I fixed it and added PETS 2022, hopefully correctly.
=> Corrected dates for PETS

_data/conferences.yml
Hi, I noticed that the winter deadline for CSF 2022 differs from the official website ([link](https://www.ieee-security.org/TC/CSF2022/cfp.html)):
```
Important Dates AoE (UTC-12h)
[...]
Winter cycle:
February 4th, 2022: paper submission deadline
April 8th, 2022: author notification
```
**Changes**:
- Fix date
- Add timezone (UTC+12 in the code)
=> Fix CSF 2022 winter deadline

README.md, _data/conferences.yml, index.html, static/js/main.js
Related to my previous issue #90 . It would be nice to show all the deadlines of multi-deadline conferences at once and not hide the deadlines that are not the nearest one. use case: 5 days before the deadline you are likely more interested in the next deadline after the nearest one.
Breaking change: we **require** that every `deadline` field in
`conferences.yml` is a real yaml list (e.g., `["2022-..."]` for single
deadlines).
We iterate over every conference and every deadline to create an entry
for every conference/deadline pair. The deadline is identified by the
index into the `deadline` list in the yaml.
some screenshots on what it looks like:
=> Show all deadlines of multi-deadline conferences at once.

static/js/main.js
My Javascript skills aren't that great and I still haven not figured out the bug. Maybe an issue with the `== null` checks? I don't really know why they are there anyway? Shouldn't accessing `a.id` give an error if `a == null`?
Anyway, this change seems to fix the sorting in chrome :shrug: #54
=> fix for sorting in chrome

_data/conferences.yml
Hi!
I suggest adding the (7th) [Security Standardisation Research Conference 2022](https://ssr2022.com). The [CfP](https://ssr2022.com/cfp/) is covering security broadly with a focus on standardisation, incl. crypto and privacy aspects.
Thanks for running this!
=> Add SSR 2022

_data/conferences.yml
2022 Asian Hardware Oriented Security and Trust Symposium
More information can be found here: http://asianhost.org/2022
Thank you!
=> Add AsianHOST 2022

_data/conferences.yml
Added AsiaCCS 2023, per https://asiaccs2023.org/
=> Update AsiaCCS 2023

_data/conferences.yml, _data/types.yml
I added added 2 tags
`Workshop`, and `Conference`
So that we can distinguish between workshops and conferences. This makes it more acceptable to add workshop pull requests.
=> Add tags for workshop and conference distinguishment

_data/conferences.yml
Deadline for AsiaCCS has been extended, cf. https://asiaccs2023.org/
=> Adjusted deadlines for AsiaCCS

_data/conferences.yml
Added the SpaceSec workshop that is co-located with NDSS Symposium 2023.
=> SpaceSec23 at NDSS 2023

_data/conferences.yml
This set of commits will fix a typo and add the following conferences:
- SACMAT
- ARES
- CODASPY
- DBSec
- ASIACCS
- The Web Conference
=> Add several conferences

_data/conferences.yml
I've added an entry for the SILM workshop (with Euro S&P) -- thanks already for putting it on the deadlines list.
There is a "/" in the workshop name -- does this work or does it need escaping?
Cheers,
JT
=> added SILM2023

index.html, static/js/main.js
Hi,
currently, the tag system (used for conference filtering) shows an entry if it matches at least one of the selected tags. This isn't particularly helpful in all cases. For example, consider I want to submit a crypto paper to a workshop. Selecting "Crypto" and "Workshop" will show all entries that are either tagged with "Crypto" or "Workshop" -- but I don't really want to see conferences tagged with "Crypto" in this case.
This pull request is a proof of concept (I'm not into JS or anything) of how this behavior could be changed: Only entries that match *all* tags selected by the user are displayed, for example, only entries that are both a "Workshop" and "Crypto".
If no tag is selected, all entries are displayed (no more precise filtering desired). Consequently, I've changed the …
=> Rework tag filtering: display only entries matching all tags

_data/conferences.yml
Due to the clash with CCS dates, we changed the dates of the conference.
=> Changed dates for ISC'23

_data/conferences.yml
Updated WPES workshop entry for their 22nd even held at CCS23. 
Note: the deadline on the website and autochair does not include a timezone, thus I've excluded it in this commit. The exact time may be off.
=> Updated WPES to '23

_data/conferences.yml
The deadline was extended to Sept. 22
=> Update Sensors S&P

_data/conferences.yml
CCS second review deadline has been postponed to April 29th: https://www.sigsac.org/ccs/CCS2024/call-for/call-for-papers.html
=> Update CCS 2nd deadline

_data/conferences.yml
It is Nov 14, not Dec 14 https://www.ieee-security.org/TC/SP2025/cfpapers.html
=> Fix deadline for Oakland 2025

_data/conferences.yml
The website is at [https://eurousec24.kau.se/](https://eurousec24.kau.se/)
The conference has proceedings (will be published in ACM Digital Library)
=> Add EuroUSEC2024 conference

_data/conferences.yml
I had put `Etc/UTC-2` as the timezone for TCC.
Noticed both Apple Calendar and Fantastical showed the wrong event times for TCC when importing the ics file. 
- Apple Calendar ignored the timezone specification and (I think) just took the specified time relative to my current timezone. 
- Fantastical seems to have interpreted the specified time as UTC.
- The website showed the correct time.
I've traced the issue to the timezone specification, which I had put as `Etc/UTC-2`, but _should_ have put as `Etc/GMT-2` (since the latter style does not seem to run into issues for other conferences).
The commit changes the time zone for TCC and for the one other conference that used a `Etc/UTC±x` specification (to avoid copy/paste errors in the future).
=> Fix timezone format (GMT instead of UTC)

_data/conferences.yml
My name is Viet Vo, an organizing team member of AsiaCCS 2025.
We update the _data.yml to update the second deadline of AsiaCCS 2025.
This is to avoid the same submission date with ACNS 2025.
This update is inline with our main website. You can see from here
https://asiaccs2025.hust.edu.vn/important-dates/
showing that the second deadline is 20 Jan 2025.
=> update the second deadline for the AsiaCCS 2025 to be 20 Jan 2025

_data/conferences.yml
The time zone is currently listed as GMT-11, but, [according to the CfP](https://petsymposium.org/cfp25.php), "All deadlines are 23:59:59 Anywhere on Earth (UTC-12)"
=> Fix PETS time zone

_data/conferences.yml
Extend the deadline of CPSIoTSec till July 18, 2024.
=> Extend the deadline of CPSIoTSec

_data/conferences.yml
This pull request adds [ACM SAC 2025 (The 40th ACM/SIGAPP Symposium On Applied Computing) ](https://www.sigapp.org/sac/sac2025/).
=> Add ACM SAC 2025

ical/deadlines-all.ical, ical/deadlines-crypto.ical, ical/deadlines-priv.ical, ical/deadlines-sec.ical
This pull request fixes the iCal implementation by handling `%Y` as indicated in https://github.com/sec-deadlines/sec-deadlines.github.io/pull/319#issuecomment-2204609619 (fixes #324 )
=> Handle %Y placeholder in iCal templates

_data/conferences.yml
Could you please update the _data/conferences.yml ?
The entry IWSEC has been updated for the 20th Int. Workshop on Security in November 2025. Venue is Fukuoka in Japan.
=> IWSEC entry updated for IWSEC 2025

_data/conferences.yml
The deadline for SACMAT 2025 has been extended to March 31, 2025, from March 24, 2025.
=> Updated the deadline for SACMAT 2025

_data/conferences.yml
Deadline for [SAFER](https://2025.ares-conference.eu/program/safer/) (ARES Workshop) extended to 5 May
=> Extended Deadline for SAFER (ARES Workshop)

_data/conferences.yml
Final deadline extension to May 12 for SAFER (ARES 2025 Workshop): [Workshop site link](https://2025.ares-conference.eu/program/safer/)
=> Final Deadline Extension for SAFER (ARES 2025 Workshop)

_data/conferences.yml
According to the [CfP](https://sp2026.ieee-security.org/cfpapers.html) an abstract registration is required.
=> Add comment about abstract registration to S&P (Oakland) 2026
