sec-deadlines/sec-deadlines.github.io

_data/conferences.yml

As per preliminary CFP at https://www.usenix.org/conference/usenixsecurity18/call-for-papers.
Please check if the timezone format is correct, I am not 100% sure if this is the right format.

Add usenix deadline

---

_data/conferences.yml

It is an IEEE workshop co-located with Oakland. Thanks!

Adding Safethings 2019

---

_data/conferences.yml

All the deadlines are already over, but I figured it'd be good to update them anyway.

Update RAID, ESORICS, ACNS

---

_data/conferences.yml

Adding the two NDSS deadlines and updating to 2020 conference.

Update NDSS conference deadlines

---

_data/conferences.yml

Add the date and direct link to the DSN 2020 conference

Fix DSN 2020 URL and date

---

_data/conferences.yml

Replaced WiSec 2019 with WiSec 2020.

Include WiSec 2020

---

_data/conferences.yml

Both have new CFPs for 2020. Assuming they still go as planned :-)

Update RAID, ESORICS and ACSAC

---

_data/conferences.yml

Accidently left the ACSAC year at 2019, fixed.
Added IMC 2020.

Fix ACSAC, add IMC 2020, NDSS 2021

---

_data/conferences.yml

CFP was updated with a revised deadline for June.

added new USENIX Security deadline

---

_data/conferences.yml

Tentative deadlines are posted on:
https://www.sigsac.org/ccs/CCS2021/program-committee.html

Update CCS 2021 venues and deadlines

---

_data/conferences.yml

Update for WiSec 2021 dates and URLs

Updating WiSec to 2021

---

_data/conferences.yml

Added 20th International Conference on Cryptology and Network Security (CANS 2021).
In case of questions, please don't hesitate to contact me!

Added CANS 2021

---

_data/conferences.yml

Add Twenty-Fifth International Conference - Financial Cryptography and Data Security 2021

Add Financial Cryptography and Data Security 2021 conference

---

_data/conferences.yml

Hello!  Could you please add an entry for the New Security Paradigms Workshop (NSPW)?  It isn't your standard security & privacy venue, but anyone in the field should consider submitting their crazy new ideas to it.  Thanks!
--Anil

Add NSPW 2021

---

_data/conferences.yml

Following: https://www.ndss-symposium.org/ndss2022/call-for-papers/

Update for NDSS 2022

---

_data/conferences.yml

Add SAC to conference list.
https://www.sacworkshop.org/

Add SAC 2021

---

_data/conferences.yml

The 26th Nordic Conference on Secure IT Systems
Call for Papers at <https://events.tuni.fi/nordsec2021/cfp/>

Add NordSec 2021

---

_data/conferences.yml

Added IEEE EuroS&P 22 deadline

Add IEEE EuroS&P 22 deadline

---

_data/conferences.yml

Hi, the CFP of  Esorics 2022 is out so I added it. Thanks for the project! ;)

Add ESORICS 2022

---

_data/conferences.yml

I updated the NSPW deadlines for 2022.  I also got rid of the timezone as we'll be moving to AoE as other conferences have.

updating NSPW for 2022

---

index.html

I bumped the javascript libs to the latest version available through cdnjs while working on #95 in an desperate attempt to find a fix.

js dependency bump

---

_data/conferences.yml

Added the Location Privacy Workshop (LPW) 2022, co-located with IEEE Euro S&P

Added LPW 2022

---

_data/conferences.yml

Workshop on Security, Privacy, and Identity Management in the Cloud

Added SECPID 2022

---

ical/deadlines-all.ical
ical/deadlines-crypto.ical
ical/deadlines-priv.ical
ical/deadlines-sec.ical
index.html

I whipped up quick ical generation template. I have only tested with my evolution calendar app so far, but it seems to work. I think it is quite nice to also put the deadlines into my calendar.
What do you think about this feature?

[WIP] Generate iCal files for the deadlines

---

_data/conferences.yml

2022 IEEE International Symposium on Secure and Private Execution Environment Design
More information can be found here: https://seed22.engr.uconn.edu/
Thank you!

Add IEEE SEED 2022

---

_data/conferences.yml

LPW 2022 submission deadline extended to March 18. Thanks a lot!

Update LPW 2022 deadline

---

_data/conferences.yml

RAID deadline was extended today: https://twitter.com/RAID_Conference/status/1509100004304113672

Updated RAID deadline to reflect extension

---

_data/conferences.yml

Hello,
The Uni that I'm affiliated with is running this conference in a few months.  I thought I'd add it to this great resource!
Let me know if this PR is acceptable; happy to make any tweaks in case I got some of the formatting wrong etc.

Add CARDIS conference

---

_data/conferences.yml

The deadline for this conference has been extended.

Update IEEE DAPPS

---

_data/conferences.yml

NSPW deadline extended to May 30th.  Thank you!  --Anil

Update NSPW 2022 deadline to May 30th

---

_data/conferences.yml

extended deadline CNS

---

_data/conferences.yml

Hey, just wanted to add this one to the list.
Love the site, cheers!

Add SaTML Conference

---

_data/conferences.yml

Adding entry  for deadline of International Conference on Security, Privacy and Applied Cryptographic Engineering 2022 (SPACE 2022)

Update conferences.yml to add entry for SPACE 2022 deadline

---

_data/conferences.yml

Deadline for VehicleSec has been extended (https://www.ndss-symposium.org/ndss2023/submissions/cfp-vehiclesec/)
Please update it. Thanks!

Update VehicleSec deadline

---

_data/conferences.yml

This adds the WOOT 2023 deadline.

Add WOOT 2023 deadline

---

_data/conferences.yml

Cas Cremers announced preliminary call for papers for CCS '23 on Twitter: https://twitter.com/CasCremers/status/1604978026378252288

add preliminary CCS 2023 cfp

---

_data/conferences.yml

Extended the deadline for SpaceSec23 to Jan 13 2023

Added SpaceSec deadline extension

---

_data/conferences.yml

adding S&P dates for 2024, as shown on https://sp2024.ieee-security.org/cfpapers.html

add S&P 2024

---

_data/conferences.yml

The link to the conference was incorrect. Also, the deadline is extended.

Update AFRICACRYPT details

---

_data/conferences.yml

Update of NDSS with the upcoming submission dates for NDSS24 on Apr19 and Jun28 as announced on twitter: https://twitter.com/NDSSSymposium/status/1631344704682958850/photo/1 The full CfP will come out shortly

Submission dates for NDSS24

---

_data/conferences.yml

Added deadline for ACSAC 2023.

Add ACSAC 2023 deadline.

---

_data/conferences.yml

Added AsiaCCS 2024 and fixed a few Crypto conf errors (example: Usenix, CCS etc)

Added AsiaCCS 2024

---

_data/conferences.yml

Deadline was extended to Wednesday, March 29, 2023 11:59:59pm

Extend RAID deadline

---

_data/conferences.yml

Hey, I've added the FUZZING workshop coming up in a couple of weeks

add FUZZING'23 workshop

---

_data/conferences.yml

Added WASP - Workshop on Attacks and Software Protection @ ESORICS 2023

Added WASP @ ESORICS 2023

---

_data/conferences.yml

As Spring cycle deadline (May 15) is approaching.

Adding CSF 2024

---

_data/conferences.yml

First deadline (May 31) is approaching

Add PETS 2024

---

_data/conferences.yml

add asiacrypt 2023

---

_data/conferences.yml

https://sites.google.com/view/secai2023

Adding SECAI 2023 workshop

---

_data/conferences.yml

Adding TrustCom 2023 (notice received via the NetSoft mailing list a few weeks ago).

Add TrustCom 2023

---

_data/conferences.yml

Updates:
- Add IACR Transactions on Symmetric Cryptology (ToSC) or FSE 2024
- Add/update CANS 2023

update cans and add fse

---

_data/conferences.yml

PC decided to extend deadlines for latincrypt.

LATINCRYPT UPDATED DEADLINES conferences.yml

---

_data/conferences.yml

DPM and CBT workshop from ESORICS 2023

Add DPM and CBT workshops

---

_data/conferences.yml

Extended deadline for DPM and CBT workshops (from ESORICS 2023)

Deadline extension for DPM and CBT workshops (ESORCS)

---

_data/conferences.yml

Can you please update PAVeTrust?
Many thanks!

PAVeTrust 2023

---

_data/conferences.yml

Added Wisec 2024

---

_data/conferences.yml

Added SpaceSec 2024, 1st and 2nd deadline

Added SpaceSec 2024

---

_data/conferences.yml

3rd workshop on robust malware analysis, co-located with EuroS&P

WoRMA workshop deadline

---

_data/conferences.yml

Added the deadline for the Workshop on Automotive Cyber-Security, co-located with the IEEE European Symposium on Security and Privacy

Added ACSW

---

_data/conferences.yml

Here's the CfP: https://www.usenix.org/conference/soups2024/call-for-papers

Update SOUPS for 2024

---

_data/conferences.yml

Updated the deadline and conference dates for NCA 2024

Updated deadline for NCA 2024

---

_data/conferences.yml

7th Workshop on System Software for Trusted Execution (SysTEX 2024), co-located with IEEE EuroS&P 2024.

SysTEX workshop deadline

---

_data/conferences.yml

This pull request adds IoT-SECFOR 2024

Add IoT-SECFOR 2024

---

_data/conferences.yml

SILM 2024: Update conferences.yml

---

_data/conferences.yml

This pull request adds ICISS 2024 conference

Add ICISS conference

---

_data/conferences.yml

Add Mal-IoT 2024

---

_data/conferences.yml

Updated the S&P deadline with CFP: [https://sp2025.ieee-security.org/cfpapers.html](https://sp2025.ieee-security.org/cfpapers.html)

Add S&P 2025 deadline.

---

_data/conferences.yml

Updated Wisec (deadline extended)
Added CPSS

Update conferences.yml (updated Wisec)

---

_data/conferences.yml

Add ACSAC 2024

---

_data/conferences.yml

Deadline for Mal-IoT 2024 updated after extension. Thanks!

Update Mal-ioT 2024 deadline

---

_data/conferences.yml

announced on https://systex24.github.io/

SysTEX deadline extension.

---

_data/conferences.yml

https://cset24.isi.edu/cfp.html

Adding CSET 2024 workshop

---

_data/conferences.yml

Update the EDId workshop Link

---

_data/conferences.yml

Added ISC 2024 to the the conferences yml. 
Thanks

Added ISC 2024

---

_data/conferences.yml

Add QSNS 2024 Workshop

---

_data/conferences.yml

Adjusted the SciSec2024 conference deadline as it is extended

Update SciSec2024 deadline

---

_data/conferences.yml

extended submission deadline: April 28, 2024 23:59 UTC
Thank you for adding to the repository

IWSEC 2024

---

_data/conferences.yml

Adding submission deadline for the upcoming symposium on applications of contextual integrity

Adding info on the privacy symposium on Applications of Contextual Integrity 

---

_data/conferences.yml

CheckMATE @ ACM CCS 2024
Research on offensive and defensive techniques in the context of Man At The End (MATE) attacks

CheckMATE @ ACM CCS 2024

---

_data/conferences.yml

Deadline extension announced for ISC 2024 (new deadline June 13, 2024)

Updated ISC 2024 deadline extension

---

_data/conferences.yml

As a graduate student, I wish all contributors good luck in having their papers accepted.

Add IEEE CNS 2024

---

_data/conferences.yml

Updated info for DPM and CBT workshops for 2024

Update DPM and CBT workshops

---

_data/conferences.yml

Thank you for the awesome project!
I'm one of the web chairs for the Cyber Security in Cars Workshop (CSCS) at CCS '24, and I'd be happy to add our conference to the tracker.

Cyber Security in Cars Workshop (CSCS) 2024

---

_data/conferences.yml

Updating AISec workshop deadline 7 July.

AISec Workshop deadline extension

---

_data/conferences.yml

We extended the submission deadline.

[CheckMATE 24] Extended submission deadline

---

_data/conferences.yml

This pull request adds the IFIP SEC conference.

Add IFIP SEC conference

---

_data/conferences.yml

Add CCSW 2024 (ACM Cloud Computing Security Workshop). Thanks!

Add CCSW 2024

---

_data/conferences.yml

This pull request updates the deadline for ICISS 2024 conference

Update deadline for ICISS 2024

---

_data/conferences.yml

Update CCSW 2024 deadline to new extended one.

Update CCSW 2024 deadline

---

_data/conferences.yml

https://pqcrypto2025.iis.sinica.edu.tw/

Add PQCrypto 2025

---

_data/conferences.yml

Updating the EuroS&P deadline (see https://eurosp2025.ieee-security.org/)

Add EuroS&P 2025 deadline

---

_data/conferences.yml

Reference: https://www.sigapp.org/sac/sac2025/index.php

Extended deadline of ACM SAC 2025

---

_data/conferences.yml

I added the CloudResIOT-Workshop co-located with the 34th International Conference on Computer Communications and Networks (ICCCN 2025)

Added cloudresiot

---

_data/conferences.yml

Added SAFE-ML

---

_data/conferences.yml

fixed itasec not being 10 years ago :D

---

_data/conferences.yml

There's still more to be done. you can accept or let me keep committing.

Cleaning up a bunch of outdated workshops. 

---

_data/conferences.yml

Included the description for ACSW'25

Added ACSW'25

---

_data/conferences.yml

Added Crypto Valley Conference 2025
https://cryptovalleyconference.com/call-for-papers

Added CVC'25

---

_data/conferences.yml

Update conferences.yml to add SafeThings 2025

---

_data/conferences.yml

Added SeRIM 2025 (https://st.fbk.eu/events/SeRIM2025/).

Add SeRIM 2025

---

_data/conferences.yml

Added WEIS 2025
The 24th Annual Workshop on
the Economics of Information Security
http://kmlabcw.iis.u-tokyo.ac.jp/weis/2025/index.html

Added WEIS

---

_data/conferences.yml

CfP: https://www.usenix.org/conference/soups2025/call-for-papers

Update SOUPS for 2025

---

_data/conferences.yml

Update QSNS 2025 Workshop

---

_data/conferences.yml

Add the dates for the 2025 edition of the EDId workshop.

Update EDId workshop

---

_data/conferences.yml

Added info about APKC, a workshop held in conjunction with AsiaCCS.
https://iseclab.ec.t.kanazawa-u.ac.jp/en/APKC2025.html

Added workshop info: APKC

---

_data/conferences.yml

CfP: https://privaci.info/symposium/2025/cfp.html

Update PrivaCI for 2025

---

_data/conferences.yml

Adding the details for ACM SACMAT 2025

Add ACM SACMAT 2025

---

_data/conferences.yml

Add the 10th Malicious Software and Hardware in Internet of Things Workshop. Please merge. Thanks!

Add MAL-IoT

---

_data/conferences.yml

We've published the extended submission deadline, and would like to see that date appear on the website.

extended submission deadline ARES'25

---

_data/conferences.yml

Changed deadline of Mal-IoT 2025 to reflect extension.

Update Mal-IoT 2025 deadline

---

_data/conferences.yml

For some reason their deadline is at noon **GMT**.

Wake up, sweetie: new AsiaCrypt CFP just dropped

---

_data/conferences.yml

Add SAFER (ARES Workshop): https://2025.ares-conference.eu/program/safer/

Add SAFER Workshop (co-located with ARES)

---

_data/conferences.yml

update secdev'25 description and deadline

Update ddl for secdev'25

---

_data/conferences.yml

I have added the MIST workshop event co-located with ESORICS 2025.

MIST Workshop added

---

_data/conferences.yml

update for NSPW 2025

---

_data/conferences.yml

Hi,
The deadline for Lightsec2025 has been updated to 18-04-2025 and this update is requested in this pull request.
Thanks

Lightsec 2025 deadline updated

---

_data/conferences.yml

Updated info for CBT workshop for 2025

Update CBT workshop

---

_data/conferences.yml

Updating USENIX as per the info from https://www.usenix.org/conference/usenixsecurity26

Update USENIX (https://www.usenix.org/conference/usenixsecurity26)

---

_data/conferences.yml

Updated Latincrypt's deadline to reflect current extension.

Update latincrypt deadline (extended)

---

_data/conferences.yml

CheckMATE @ ACM CCS 2025
Research on offensive and defensive techniques in the context of Man At The End (MATE) attacks

CheckMATE @ ACM CCS 2025

---

_data/conferences.yml

The deadline has been extended for a week.

EDId 2025 submission deadline updated

---

_data/conferences.yml

Update TrustCom 2025

---

_data/conferences.yml

Final deadline extension for Latincrypt 2025 updated.

Latincrypt deadline extension

---

_data/conferences.yml

HAIPS @ ACM CCS 2025
[1st Workshop on Human-Centered AI Privacy and Security](https://haips.com)

HAIPS @ ACM CCS 2025

---

_data/conferences.yml

Updated the extended deadline for CRISIS2025

Updated deadline for CRISIS2025

---

_data/conferences.yml

Extended OPTIMIST deadline

---

_data/conferences.yml

Hi, 
I am the TPC co-chair of ACNS 2026 (https://acns2026.github.io/). 
I added submission dues for ACNS 2026. Also, PR accidentally removed trailing whitespace. 
Thanks for your service. 
Regards, Kangkook

acns2026 added.

---

_data/conferences.yml

https://cset25.isi.edu/cfp.html

Update CSET for 2025

---

_data/conferences.yml

Added Security Standardisation Conference 2025; Passau, Germany

Added SSR 2025
